Update infra-creation.yml

diff --git a/.github/workflows/infra-creation.yml b/.github/workflows/infra-creation.yml
--- a/.github/workflows/infra-creation.yml
+++ b/.github/workflows/infra-creation.yml
@@ -22,7 +22,7 @@ on:
 permissions:
   contents: read
   pull-requests: write 
-  id-token: write
+  
 
 jobs:
   terraform:
@@ -36,108 +36,101 @@ jobs:
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
         with:
-          terraform_version: 1.5.5
+          terraform_version: 1.5.5    
 
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-          role-to-assume: arn:aws:iam::010928202531:role/open_id_connect
-          role-session-name: githubactions
-          aws-region: "us-east-1"    
-
-      # - name: Install TFLint
-      #   run: |
-      #     TFLINT_VERSION="v0.55.0"
-      #     curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
+      - name: Install TFLint
+        run: |
+           TFLINT_VERSION="v0.55.0"
+           curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
           
-      #     if [ ! -s "tflint.zip" ]; then
-      #       echo "Error: Downloaded TFLint archive is empty or invalid."
-      #       exit 1
-      #     fi
+           if [ ! -s "tflint.zip" ]; then
+             echo "Error: Downloaded TFLint archive is empty or invalid."
+             exit 1
+           fi
 
-      #     unzip tflint.zip
-      #     chmod +x tflint
-      #     sudo mv tflint /usr/local/bin/
-      #     rm tflint.zip
+           unzip tflint.zip
+           chmod +x tflint
+           sudo mv tflint /usr/local/bin/
+           rm tflint.zip
           
-      #     echo "TFLint installed successfully:"
-      #     tflint --version
+           echo "TFLint installed successfully:"
+           tflint --version
 
 
       # # Step: Run TFLint
-      # - name: Run TFLint
-      #   run: |
-      #    cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
+      - name: Run TFLint
+        run: |
+          cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
 
-      #    # Ensure .tflint.hcl exists
-      #    if [ ! -f ".tflint.hcl" ]; then
-      #       cat <<EOF > .tflint.hcl
-      #       plugin "terraform" {
-      #       enabled = true
-      #      }
-      #    EOF
-      #    fi
+          # Ensure .tflint.hcl exists
+          if [ ! -f ".tflint.hcl" ]; then
+             cat <<EOF > .tflint.hcl
+             plugin "terraform" {
+             enabled = true
+            }
+          EOF
+          fi
 
-      #    # Install TFLint plugin (Terraform)
-      #    tflint --init
+          # Install TFLint plugin (Terraform)
+          tflint --init
 
-      #    # Run TFLint with proper syntax
-      #    tflint --config .tflint.hcl
-      #   env:
-      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          # Run TFLint with proper syntax
+          tflint --config .tflint.hcl
+          env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      # checkov -d . --quiet --framework terraform
-      # Step: Install Checkov
+           checkov -d . --quiet --framework terraform
+       # Step: Install Checkov
       - name: Install Checkov
         run: |
           pip install checkov
           checkov --version
 
-      # # Step: Run Checkov Security Scan
-      # - name: Run Checkov
-      #   run: |
-      #     cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
-      #     checkov --directory . --skip-check CKV_AWS_*,CKV2_AWS_*
-      #   env:
-      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+       # Step: Run Checkov Security Scan
+      - name: Run Checkov
+        run: |
+           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
+           checkov --directory . --skip-check CKV_AWS_*,CKV2_AWS_*
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           
       # Step: Terraform Init
       - name: Terraform Init
         run: | 
           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
           terraform init
-        # env:
-        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      # Step: Run Terraform Validate (validate configuration files)
+      #Step: Run Terraform Validate (validate configuration files)
       - name: Terraform Validate
         run: |
           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
           terraform validate
-        # env:
-        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       # Step: Terraform Workspace Select
       - name: Terraform Workspace Select
         run: |
           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
           terraform workspace select ${{ github.event.inputs.environment || 'dev' }} || terraform workspace new ${{ github.event.inputs.environment || 'dev' }}
-        # env:
-        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
 
       # Step: Terraform Plan
       - name: Terraform Plan
         run: |
           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }} 
           terraform plan -var-file="${{ github.event.inputs.environment || 'dev' }}-var.tfvars" -out=tfplan
-        # env:
-        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       # Step: Checkout Repository for PR
       - name: Checkout Repository
@@ -180,6 +173,6 @@ jobs:
           cd Infra/Environments/${{ github.event.inputs.environment || 'dev' }}
           terraform init
           terraform apply -auto-approve -var-file="${{ github.event.inputs.environment || 'dev' }}-var.tfvars"
-        # env:
-        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        env:
+           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
